import os
import re
import tempfile
import time
from concurrent.futures import ThreadPoolExecutor
from PyPDF2 import PdfReader
from docx import Document
from groq import Groq

def extract_text_from_file(uploaded_file):
    """Extracts text from PDF, DOCX, and TXT files. In-memory processing only."""
    if not uploaded_file:
        return None

    filename = uploaded_file.name.lower()
    
    if filename.endswith(".txt"):
        return uploaded_file.read().decode("utf-8", errors="ignore")
    
    elif filename.endswith(".pdf"):
        pdf = PdfReader(uploaded_file)
        text = ""
        for page in pdf.pages:
            extracted = page.extract_text()
            if extracted:
                text += extracted + "\n"
        return text

    elif filename.endswith(".docx"):
        doc = Document(uploaded_file)
        text = "\n".join([para.text for para in doc.paragraphs])
        return text
        
    else:
        return None

def chunk_text(text, chunk_size=2000, overlap=200):
    """Splits a large text into overlapping chunks."""
    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end]
        chunks.append(chunk)
        start += chunk_size - overlap
    return chunks

def process_chunk(chunk, instruction):
    """Processes a single text chunk using Groq Llama 3.3."""
    try:
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            return "Error: GROQ_API_KEY not found in environment."
            
        client = Groq(api_key=api_key)
        res = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": f"{instruction}\n\nCONTENT:\n{chunk}"}],
            temperature=0.2
        )
        return res.choices[0].message.content
    except Exception as e:
        return f"Chunk processing failed: {e}"

def validate_response_for_hallucination(response: str, prompt: str) -> str:
    """Post-processes AI responses to catch and flag likely hallucinations."""
    warnings = []
    urls_in_response = re.findall(r'https?://[^\s\)\"\']+', response)
    urls_in_prompt = re.findall(r'https?://[^\s\)\"\']+', prompt)
    
    fake_url_patterns = [
        "example.com", "yoursite.com", "myapp.com"
    ]
    
    for url in urls_in_response:
        if url not in urls_in_prompt:
            if any(pattern in url for pattern in fake_url_patterns):
                warnings.append(f"⚠️ **Note:** The URL `{url}` was generated by AI and may not be real.")
    
    fake_stat_patterns = [
        r'\d+% of (users|people|companies|businesses)',
        r'according to (recent|latest|new) (studies|research|reports)',
        r'studies show that',
        r'research (shows|suggests|indicates) that \d+'
    ]
    
    for pattern in fake_stat_patterns:
        if re.search(pattern, response.lower()):
            warnings.append("⚠️ **Note:** Statistics mentioned above should be independently verified.")
            break
            
    if warnings:
        response += "\n\n---\n" + "\n".join(warnings)
    
    return response

def run_analysis(text, prompt, depth="Standard Analysis", document_type="General Document Scan"):
    """
    Runs multi-threaded chunk analysis based on depth, consolidates the output, 
    and applies hallucination checks.
    """
    if not text or not text.strip():
        return "Error: No extractable text found in the document."

    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return "Error: GROQ_API_KEY missing. Please configure .env"

    # Adjust chunking based on requested depth
    if depth == "Quick Scan (30 seconds)":
        chunk_size = 4000
        overlap = 100
        model = "llama-3.3-70b-versatile"
    elif depth == "Deep Review (2-3 minutes)":
        chunk_size = 1500
        overlap = 300
        model = "llama-3.3-70b-versatile" # Using 70b for deeper review
    else: # Standard
        chunk_size = 2000
        overlap = 200
        model = "llama-3.3-70b-versatile"

    chunks = chunk_text(text, chunk_size=chunk_size, overlap=overlap)
    partial_results = []

    # Parallel processing of chunks with a 2-second delay between calls to avoid rate limits
    with ThreadPoolExecutor(max_workers=5) as executor:
        futures = []
        for chunk in chunks:
            futures.append(executor.submit(process_chunk, chunk, prompt))
            time.sleep(2)
        for future in futures:
            partial_results.append(future.result())
            
    combined = "\n\n".join(partial_results)
    
    # Final consolidation
    try:
        import datetime
        analysis_date = datetime.date.today().strftime('%Y-%m-%d')
        
        client = Groq(api_key=api_key)
        res = client.chat.completions.create(
            model=model,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are BORA, a senior South African legal and business analyst.\n"
                        "Your job is to COMBINE and PRESERVE all content from the chunk analyses below into one complete final report.\n"
                        "Adhere EXACTLY to the formatting requested in the prompt and follow this MANDATORY OUTPUT STRUCTURE.\n\n"
                        "GENERAL RULE: When outputting section headers (such as EXECUTIVE SUMMARY, CRITICAL RISKS, MODERATE RISKS, LOW RISKS), do NOT repeat or include any formatting instructions, constraints, or parenthetical descriptions (such as '(3 sentences max)' or '(Should negotiate)') in the header text itself. Output only the pure, plain header names. Do not include any instructions or meta-commentary in your output.\n\n"
                        "---\n"
                        "BORA RISK ANALYSIS REPORT\n"
                        f"Document Type: {document_type}\n"
                        f"Analysis Date: {analysis_date}\n"
                        f"Analysis Depth: {depth}\n"
                        "---\n\n"
                        "EXECUTIVE SUMMARY\n"
                        "Write the executive summary in no more than 3 sentences. Do not include this instruction or any meta-commentary in your output — output only the summary text itself.\n"
                        "One paragraph summarising the overall risk level and the single most important thing the user must address.\n\n"
                        "RISK SCORECARD\n"
                        "Total risks found: [number]\n"
                        "Critical (Red): [number]\n"
                        "Moderate (Amber): [number]\n"
                        "Low (Green): [number]\n"
                        "Overall risk rating: [RED/AMBER/GREEN]\n"
                        "Recommended action: [Sign/Negotiate/Do Not Sign]\n\n"
                        "---\n"
                        "CRITICAL RISKS\n"
                        "---\n\n"
                        "🔴 RISK [NUMBER]: [RISK TITLE IN CAPS]\n"
                        "Clause: [exact location]\n"
                        "Law violated: [specific act and section. If the risk violates a common-law principle rather than a specific statute (e.g. right to due process before eviction, unlawful self-help, access to courts/natural justice, unconscionable penalties under common law), name that principle explicitly, e.g. 'Common law: unlawful self-help / illegal eviction' or 'Common law: ouster of court jurisdiction (void as against public policy)'. Only use 'None' if the risk is purely a fairness/best-practice concern with no legal basis at all, and even then prefer 'General fairness concern' over 'None']\n"
                        "What it means in plain English: [one sentence a non-lawyer understands]\n"
                        "Financial impact: [estimated rand amount if possible, or \"significant\" if not]\n"
                        "What to do: [specific negotiation instruction]\n\n"
                        "---\n"
                        "MODERATE RISKS\n"
                        "---\n\n"
                        "🟡 RISK [NUMBER]: [RISK TITLE IN CAPS]\n"
                        "Clause: [exact location]\n"
                        "Concern: [what is problematic]\n"
                        "What to do: [specific instruction]\n\n"
                        "---\n"
                        "LOW RISKS\n"
                        "---\n\n"
                        "🟢 [RISK TITLE]: [one sentence why acceptable]\n\n"
                        "---\n"
                        "NEGOTIATION PRIORITY LIST\n"
                        "---\n\n"
                        "Numbered list of what to negotiate first. Number 1 is most important. Maximum 10 items.\n"
                        "Each item has:\n"
                        "- What to negotiate\n"
                        "- What to ask for specifically\n"
                        "- What to accept as minimum\n\n"
                        "---\n"
                        "RED LINE CLAUSES\n"
                        "---\n\n"
                        "List any clauses so dangerous that the user should refuse to sign if not removed.\n"
                        "If none exist say: \"No absolute red line clauses found.\"\n\n"
                        "---\n"
                        "DISCLAIMER\n"
                        "---\n\n"
                        "⚖️ IMPORTANT DISCLAIMER\n"
                        "This analysis is generated by BORA AI and is provided for informational purposes only.\n"
                        "It does not constitute legal advice. BORA is a technology tool not a law firm.\n"
                        "For legally binding advice please consult a qualified South African attorney before signing any contract.\n"
                        "We accept no liability for decisions made based on this analysis.\n\n"
                        "STRICT DEDUPLICATION RULES:\n"
                        "1. EXECUTIVE SUMMARY: There must be exactly ONE executive summary or SUMMARY section in the entire output at the top. Merge duplicate summaries.\n"
                        "2. TABLE DEDUPLICATION: Merge duplicate tables.\n"
                        "3. SECTION HEADINGS: Each section heading must appear exactly once.\n"
                        "4. LISTS: Deduplicate bullet items.\n"
                        "5. NUMBERING: Re-number all risk items sequentially (e.g., 1, 2, 3, etc.).\n"
                        "The output must read as ONE single professional report. A reader must never see the same heading twice."
                    )
                },
                {"role": "user", "content": f"Original Instructions: {prompt}\n\nChunk Analyses:\n{combined}"}
            ],
            temperature=0.2,
            max_tokens=4000
        )
        final_report = res.choices[0].message.content
        return validate_response_for_hallucination(final_report, prompt)
    except Exception as e:
        return f"Consolidation Error: {e}\n\nPartial Results:\n{combined[:2000]}..."

def get_document_stats(uploaded_file):
    """Estimates page count, word count, and recommends analysis depth."""
    pages = 1
    words = 0
    try:
        filename = uploaded_file.name.lower()
        uploaded_file.seek(0)
        
        if filename.endswith(".pdf"):
            pdf = PdfReader(uploaded_file)
            pages = len(pdf.pages)
            text = ""
            for page in pdf.pages:
                extracted = page.extract_text()
                if extracted:
                    text += extracted + " "
            words = len(text.split())
        elif filename.endswith(".docx"):
            doc = Document(uploaded_file)
            text = "\n".join([para.text for para in doc.paragraphs])
            words = len(text.split())
            pages = max(1, len(doc.paragraphs) // 30)
        elif filename.endswith(".txt"):
            text = uploaded_file.read().decode("utf-8", errors="ignore")
            words = len(text.split())
            pages = max(1, words // 400)
            
        uploaded_file.seek(0)
    except Exception:
        try:
            uploaded_file.seek(0)
        except Exception:
            pass
            
    if words == 0:
        words = 100 # Fallback
        
    # Recommending depth
    if words > 5000:
        rec_depth = "Deep Review (2-3 minutes)"
    elif words > 2000:
        rec_depth = "Standard Analysis (60 seconds)"
    else:
        rec_depth = "Quick Scan (30 seconds)"
        
    return {
        "pages": pages,
        "words": words,
        "recommended_depth": rec_depth
    }

def parse_scorecard(results):
    """Parses risk counts and overall ratings from the report text to feed the UI metrics."""
    import re
    critical = 0
    moderate = 0
    low = 0
    overall = "GREEN"
    
    crit_match = re.search(r"Critical\s*(?:\(Red\))?:\s*(\d+)", results, re.IGNORECASE)
    if crit_match:
        critical = int(crit_match.group(1))
        
    mod_match = re.search(r"Moderate\s*(?:\(Amber\))?:\s*(\d+)", results, re.IGNORECASE)
    if mod_match:
        moderate = int(mod_match.group(1))
        
    low_match = re.search(r"Low\s*(?:\(Green\))?:\s*(\d+)", results, re.IGNORECASE)
    if low_match:
        low = int(low_match.group(1))
        
    overall_match = re.search(r"Overall\s*risk\s*rating:\s*(RED|AMBER|GREEN)", results, re.IGNORECASE)
    if overall_match:
        overall = overall_match.group(1).upper()
    else:
        # Fallbacks
        if "Overall risk rating: RED" in results or "overall risk level is RED" in results or "🔴 HIGH RISK" in results:
            overall = "RED"
        elif "Overall risk rating: AMBER" in results or "overall risk level is AMBER" in results or "🟡 MODERATE RISK" in results:
            overall = "AMBER"
            
    if critical > 0 or overall == "RED":
        recommended = "⛔ Do Not Sign Yet"
        overall = "RED"
    elif moderate > 0 or overall == "AMBER":
        recommended = "⚠️ Negotiate First"
        overall = "AMBER"
    else:
        recommended = "✅ Reasonable to Sign"
        overall = "GREEN"
    return {
        "critical": critical,
        "moderate": moderate,
        "low": low,
        "overall": overall,
        "recommended": recommended
    }
