import os
import re
import tempfile
from concurrent.futures import ThreadPoolExecutor
from PyPDF2 import PdfReader
from docx import Document
from groq import Groq

def extract_text_from_file(uploaded_file):
    """Extracts text from PDF, DOCX, and TXT files. In-memory processing only."""
    if not uploaded_file:
        return None

    filename = uploaded_file.name.lower()
    
    if filename.endswith(".txt"):
        return uploaded_file.read().decode("utf-8", errors="ignore")
    
    elif filename.endswith(".pdf"):
        pdf = PdfReader(uploaded_file)
        text = ""
        for page in pdf.pages:
            extracted = page.extract_text()
            if extracted:
                text += extracted + "\n"
        return text

    elif filename.endswith(".docx"):
        doc = Document(uploaded_file)
        text = "\n".join([para.text for para in doc.paragraphs])
        return text
        
    else:
        return None

def chunk_text(text, chunk_size=2000, overlap=200):
    """Splits a large text into overlapping chunks."""
    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end]
        chunks.append(chunk)
        start += chunk_size - overlap
    return chunks

def process_chunk(chunk, instruction):
    """Processes a single text chunk using Groq Llama 3.1."""
    try:
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            return "Error: GROQ_API_KEY not found in environment."
            
        client = Groq(api_key=api_key)
        res = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "user", "content": f"{instruction}\n\nCONTENT:\n{chunk}"}],
            temperature=0.2
        )
        return res.choices[0].message.content
    except Exception as e:
        return f"Chunk processing failed: {e}"

def validate_response_for_hallucination(response: str, prompt: str) -> str:
    """Post-processes AI responses to catch and flag likely hallucinations."""
    warnings = []
    urls_in_response = re.findall(r'https?://[^\s\)\"\']+', response)
    urls_in_prompt = re.findall(r'https?://[^\s\)\"\']+', prompt)
    
    fake_url_patterns = [
        "example.com", "yoursite.com", "myapp.com"
    ]
    
    for url in urls_in_response:
        if url not in urls_in_prompt:
            if any(pattern in url for pattern in fake_url_patterns):
                warnings.append(f"⚠️ **Note:** The URL `{url}` was generated by AI and may not be real.")
    
    fake_stat_patterns = [
        r'\d+% of (users|people|companies|businesses)',
        r'according to (recent|latest|new) (studies|research|reports)',
        r'studies show that',
        r'research (shows|suggests|indicates) that \d+'
    ]
    
    for pattern in fake_stat_patterns:
        if re.search(pattern, response.lower()):
            warnings.append("⚠️ **Note:** Statistics mentioned above should be independently verified.")
            break
            
    if warnings:
        response += "\n\n---\n" + "\n".join(warnings)
    
    return response

def run_analysis(text, prompt, depth="Standard Analysis"):
    """
    Runs multi-threaded chunk analysis based on depth, consolidates the output, 
    and applies hallucination checks.
    """
    if not text or not text.strip():
        return "Error: No extractable text found in the document."

    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return "Error: GROQ_API_KEY missing. Please configure .env"

    # Adjust chunking based on requested depth
    if depth == "Quick Scan (30 seconds)":
        chunk_size = 4000
        overlap = 100
        model = "llama-3.1-8b-instant"
    elif depth == "Deep Review (2-3 minutes)":
        chunk_size = 1500
        overlap = 300
        model = "llama-3.3-70b-versatile" # Using 70b for deeper review
    else: # Standard
        chunk_size = 2000
        overlap = 200
        model = "llama-3.1-8b-instant"

    chunks = chunk_text(text, chunk_size=chunk_size, overlap=overlap)
    partial_results = []

    # Parallel processing of chunks
    with ThreadPoolExecutor(max_workers=5) as executor:
        futures = [executor.submit(process_chunk, chunk, prompt) for chunk in chunks]
        for future in futures:
            partial_results.append(future.result())
            
    combined = "\n\n".join(partial_results)
    
    # Final consolidation
    try:
        client = Groq(api_key=api_key)
        res = client.chat.completions.create(
            model=model,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are BORA, a senior South African legal and business analyst. "
                        "Your job is to COMBINE and PRESERVE all content from the chunk analyses below into one complete final report. "
                        "Adhere EXACTLY to the formatting requested in the prompt. "
                        "DO NOT summarise away critical risks. Combine duplicates logically. "
                        "STRICT DEDUPLICATION RULES:\n"
                        "1. EXECUTIVE SUMMARY: There must be exactly ONE executive summary or SUMMARY section in the entire output. It must appear at the very end. If multiple summaries exist in the input, merge them into one paragraph keeping only the unique information. Delete all but the final merged version.\n"
                        "2. TABLE DEDUPLICATION: If the same table appears more than once, merge all rows into a single table. Remove any row that is an exact duplicate of another row. The merged table replaces all instances.\n"
                        "3. SECTION HEADINGS: Each section heading must appear exactly once. If a heading appears multiple times, merge all content under that heading into one section.\n"
                        "4. LISTS: If the same item appears in multiple bullet point lists, keep it only once in the final merged list.\n"
                        "5. NUMBERING: After merging, re-number all risk items sequentially from RISK-001 through to the final item. No gaps. No duplicates.\n"
                        "6. FINAL CHECK: Before returning the output, mentally scan for any heading that appears more than once. If found, merge immediately.\n"
                        "The output must read as ONE single professional report. A reader must never see the same heading twice."
                    )
                },
                {"role": "user", "content": f"Original Instructions: {prompt}\n\nChunk Analyses:\n{combined}"}
            ],
            temperature=0.2,
            max_tokens=4000
        )
        final_report = res.choices[0].message.content
        disclaimer = """

---
⚖️ **IMPORTANT DISCLAIMER**
This analysis is generated by BORA AI and is provided for informational purposes only.
It does not constitute legal advice. BORA is a technology tool not a law firm.
For legally binding advice please consult a qualified South African attorney before signing any contract.
We accept no liability for decisions made based on this analysis.
---"""
        final_report += disclaimer
        return validate_response_for_hallucination(final_report, prompt)
    except Exception as e:
        return f"Consolidation Error: {e}\n\nPartial Results:\n{combined[:2000]}..."
